name: Build Docker image

on:
  push:
    branches:
      - main
      - master
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11  # This is similar to GitLab's 'image'
    steps:
      - uses: actions/checkout@v4
      - run: pip install --no-cache-dir -r requirements.txt
      - run: python app.py

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false   # Set to true if you want to push to Docker Hub
          tags: my-python-app:latest